/*
 * FrmJogo.java
 *
 * Created on 7 de Agosto de 2008, 09:51
 */
package jogo2;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferStrategy;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jackson
 */
public class FrmJogo1Alterado extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form FrmJogo
     */
    public FrmJogo1Alterado() {
        initComponents();

        createBufferStrategy(2);

        Thread t = new Thread(this);
        t.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmJogo1Alterado().setVisible(true);
            }
        });
    }

    public void run() {

        BufferStrategy buffer = getBufferStrategy();
        Graphics bg;

        ArrayList<Bola> minhasBolas = new ArrayList<Bola>();

        for (int i = 0; i < 100; i++) {
            int x = (int) (Math.random() * getWidth());
            int y = (int) (Math.random() * getHeight());
            int r = (int) (Math.random() * 255);
            int g = (int) (Math.random() * 255);
            int b = (int) (Math.random() * 255);

            minhasBolas.add(new Bola(new Color(r, g, b), x, y));
        }

        long tempo;

        tempo = System.currentTimeMillis();

        while (true) {

            bg = buffer.getDrawGraphics();

            bg.setColor(Color.GREEN);
            bg.fillRect(0, 0, getWidth(), getHeight());

            for (Bola b : minhasBolas) {
                b.mover();
            }

            for (Bola b : minhasBolas) {
                b.desenhar(bg);
            }

            for (Bola b : minhasBolas) {
                b.trataColisaoForm(getWidth(), getHeight());
            }

            bg.dispose();
            buffer.show();

            try {
                Thread.sleep(20);
            } catch (InterruptedException ex) {

            }

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
